---
title: "EDA"
author: "Raphaël Morsomme"
date: "January 15, 2020"
output: pdf_document
---

```{r setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(GGally) # ggpairs()

my_standardize <- function(x) (x - mean(x, na.rm = T)) / sd(x, na.rm = T)

# longest pregnancy possible
# http://content.time.com/time/magazine/article/0,9171,797153,00.html
(375-58)/7 # 45.28
```

```{r data prep}
d <- readRDS("Longnecker.rds") %>%
  
  mutate_at(vars(center, smoking_status), factor) %>%
  select(-albumin) %>% # too many NAs
  
  filter(gestational_age <= 46) %>% # more accurate treatment would be to allow for error in measurement since the number of weeks is only estimated (there is room for error)
  mutate(pre_mature = gestational_age <= 37) %>%
  
  
  # construct aggregate pcb variable: average of pcb's
  mutate_at(vars(starts_with("pcb")), my_standardize) %>% # standardize pcb's to give them all equal weight in the aggregate pcb variable
  rowwise() %>%
  mutate(pcb = mean(c(pcb_028, pcb_052, pcb_074, pcb_105, pcb_118, pcb_153, pcb_170, pcb_138, pcb_180, pcb_194, pcb_203))) %>%
  ungroup
```

```{r NA}
sum(complete.cases(d)) / nrow(d)
```

```{r plot pcb}
d %>% 
  select(dde, pcb, pcb_028 : pcb_203) %>%
  #mutate_all(~(log(. + 0.1))) %>%
  ggcorr(palette = "RdBu", label = TRUE)

d %>%
  ggplot(aes(x = pcb, y = dde)) +
  geom_point()

d %>% 
  ggplot(aes(x = pre_mature, y = pcb)) +
  geom_boxplot()

d %>%
  ggplot(aes(x = pcb, y = gestational_age)) +
  geom_jitter() +
  geom_hline(yintercept = 37)
d %>%
  ggplot(aes(x = dde, y = gestational_age)) +
  geom_jitter() +
  geom_hline(yintercept = 37)
```


```{r plots normality}
hist(log(d$dde))
hist(log(d$pcb_028))
hist(log(d$pcb_052))
hist(log(d$triglycerides))

hist(d$gestational_age)
sort(d$gestational_age, T)[1:10]
hist(d$maternal_age)
```

```{r plot fat}
d %>% 
  select(cholesterol, triglycerides, pcb, dde) %>%
  ggpairs(lower = list(continuous = wrap("points", alpha = 0.5, size = .1)))
```

