\documentclass{beamer}
\usetheme{Madrid}

%%%%% Packages %%%%%
\usepackage{algorithm}
\usepackage{csquotes}
\usepackage[round]{natbib}
\bibliographystyle{agsm}
\usepackage{algorithmic}
\usepackage{pgfpages}
\usepackage{ragged2e}
\usepackage{etoolbox}
\usepackage{lipsum}
\usepackage{subfig}
\apptocmd{\frame}{}{\justifying}{} 
\usepackage{xcolor}
\usepackage{dsfont}
\usepackage{tikz}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{subfig}
\usepackage{mathtools}
\usepackage{xcolor}
\usepackage{comment}
\usepackage{appendixnumberbeamer}
%%%%% New Commands %%%%
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\x}{\mathbf{x}}
\newcommand{\SUN}{\textrm{SUN}}
\newcommand{\X}{\mathbf{X}}
\newcommand{\T}{\textrm{T}}
\newcommand{\A}{\mathcal{A}}
\newcommand{\I}{\mathds{1}}
\newcommand{\hist}{\mathbb{H}_{t-1}}
\newcommand\myeq{\stackrel{\mathclap{\normalfont\mbox{def}}}{=}}
\def\app#1#2{%
  \mathrel{%
    \setbox0=\hbox{$#1\sim$}%
    \setbox2=\hbox{%
      \rlap{\hbox{$#1\propto$}}%
      \lower1.1\ht0\box0%
    }%
    \raise0.25\ht2\box2%
  }%
}
\def\approxprop{\mathpalette\app\relax}
%\pgfpagesuselayout{1 on 1}[a4paper,border shrink=5mm]
\title[DDE and PCB effect on Premature delivery]{Assessing Effects of Exposures to DDE and PCBs on Premature Delivery via Ordinal Logistic Regression}
\author[Morsomme, Ou, Zito]{Raphael Morsomme \and Rihui Ou \and Alessandro Zito}
\institute[Stat 723]{Case Study 1 - Stat 723}
\date{\today}
\begin{document}
<<echo=FALSE, results='hide', warning=FALSE>>=
suppressMessages(library(tidyverse))
suppressMessages(library(GGally)) # ggpairs()
suppressMessages(library(tidyimpute)) # NA imputation
suppressMessages(library(na.tools)) # NA imputation
suppressMessages(library(MASS))
suppressMessages(library(sure)) # Surrogate Residuals 
suppressMessages(library(rstanarm))
suppressMessages(library(ggpubr))
suppressMessages(library(corrplot))
suppressMessages(library(RColorBrewer))
my_standardize <- function(x) (x - mean(x, na.rm = T)) / sd(x, na.rm = T)
ggplot2::theme_set(ggplot2::theme_bw())
d = readRDS("Longnecker.rds") %>%
  mutate_at(vars(center, smoking_status), factor) %>%
  dplyr::select(-albumin) %>% # too many NAs
  # Dependent Variable
  filter(gestational_age <= 45) %>% # more accurate treatment would be to allow for error in measurement since the number of weeks is only estimated (there is room for error)
  mutate(outcome_2 = case_when(gestational_age <= 37 ~ "Pre term",
                               TRUE                  ~ "At term"),
         outcome_3 = case_when(gestational_age <= 34 ~ "0Dangerous",
                               gestational_age <= 37 ~ "1Pre term",
                               TRUE                  ~ "2At term"),
         gestgroup = case_when(gestational_age <= 34 ~ "Dangerous",
                               gestational_age <= 37 ~ "Pre term",
                               TRUE                  ~ "At term")) %>%
  mutate(outcome_3 = outcome_3 %>% factor) %>%
  mutate(gestgroup = gestgroup %>% factor) %>%
  # Aggregate PCBs
  mutate_at(vars(starts_with("pcb")), my_standardize) %>% # standardize pcb's to give them all equal weight in the aggregate pcb variable
  rowwise() %>%
  mutate(pcb = mean(c(pcb_028, pcb_052, pcb_074, pcb_105, pcb_118, pcb_153, pcb_170, pcb_138, pcb_180, pcb_194, pcb_203))) %>%
  ungroup %>%
  
  # Fat
  mutate(fat = 2.27 * cholesterol + triglycerides + 0.623) %>% # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3893492/
  
  # Exposure
  mutate(dde_env = dde / fat,
         pcb_env = pcb / fat) %>%
  # Adjusted Exposure 
  mutate(dde_env_bc = dde / log(fat),
         pcb_env_bc = pcb / log(fat)) %>%
  
  # NA
  impute_if(na.mean, is.numeric) %>%
  #impute_if(na.mode, is.character) %>% # not necessary
  
  dplyr::select(starts_with("outcome"), # Y
                starts_with("dde|pcb"), # X
                starts_with("score"), race, maternal_age, center, smoking_status, # Z
                everything())
d$race_agg = "white"
d[d$race!="white", ]$race_agg = "non white"
@
\begin{frame}
\titlepage
\end{frame}

\begin{frame}{Overview}
\tableofcontents
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Introduction                       
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
\begin{frame}{Introduction}
\begin{itemize}
\item \textcolor{red}{\textbf{Framework}}: \\
\textit{Dichlorodiphenyldichloroethylene} (DDE) and \textit{Polychlorinated Biphenyls} (PCBs) 
are chemicals that persist in the envirnoment and get stored in fatty depositis in the human tissues.\\
$\quad \Longrightarrow \ $\textcolor{blue}{Potential adverse effect on health}
\item \textcolor{red}{\textbf{Question}}:\\
\textit{Is exposure to DDE and PBCs associated with a higher chance of premature delivery in pregnant women?}
\end{itemize}
\begin{block}{Pregnancy timeline}
\begin{itemize}
\item \textbf{Dangerous preterm}:  delivery at 34 weeks or before (when main organs are underdeveloped)
\item \textbf{Preterm}: delivery beween 35 and 37 week
\item \textbf{At term}: delivery after 37 weeks
\end{itemize}
\end{block}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% The Data                       
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Data}
\begin{frame}{Data}
Data collected by 12 centers contained gestational age (in weeks) of the mother, the DDE and PCBs concentration, socio-economic info and scores (race, occupation, education, income), amount of triglycerides and cholesterol in blood and smoking status. \\
\medskip 
\textcolor{red}{\textbf{Preprocessing}}:
\begin{itemize}
\item Drop obs. with gestational age $>$ 45 (the world record)
\item Standardize and average levels of PCBs\footnote{This avoids the correlation between the PCBs. See the appendix.}
$$PCB_i = \frac{1}{11}\sum_{j=1}^{11} \frac{PCB_{ij} - mean_i(PCB_{ij})}{sd_i(PCB_{ij})}$$
\item Mean impute of occupation, education and income scores 
\item Aggregate race into $race = 1$ if white and $race=0$ if non-white
\end{itemize}
\medskip
$\quad \Longrightarrow$ \textcolor{blue}{Total obs.} = \textbf{2336}
\end{frame}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}{Data}
\small
\begin{itemize}
\item \textbf{Our dependent varible is}:
$$gestgroup_i = 
\begin{cases}
0 & if \ \textrm{Dangerous preterm} \\
1 & if \ \textrm{Preterm} \\
2 & if \ \textrm{At term} 
\end{cases}$$
\item To account for triglyceredes and cholesterol, we introduce an \textbf{adjusted measure for} $PCB$ \textbf{and} $DDE$ by:
\begin{enumerate}
\item Computing total lipids using Phillips et al.(1989) and Bernert et al.(2007) forumula $$lipid_i =  2.27 * cholesterol_i + triglycerides_i + 0.623$$ 
\item Setting\footnote{The choice of the log comes from a Box-Cox analysis of the log-likelihood, as in Li, Longnecker and Dunson (2013)}
$$adjDDE_i = \frac{DDE_i}{log(lipid_i)} \qquad adjPCB_i = \frac{PCB_i}{log(lipid_i)}$$
\end{enumerate}
\end{itemize}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% EDA                    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}{EDA (I) - Exposures and gestational groups by race}
<<echo=FALSE, fig.align='center', fig.height=3, fig.width=5>>=
# PCB and outcome_3
pcb_race = ggplot(d) +
  geom_boxplot(aes(x=gestgroup,y=pcb_env_bc, fill=race_agg))+
  ylab("Adjusted PCB")+
  labs(fill="Race")+
  xlab("")+
  facet_grid(~"Adjusted PCB by group")
# DDE and outcome_3
dde_race = ggplot(d) +
  geom_boxplot(aes(x=gestgroup,y=dde_env_bc, fill=race_agg))+
  ylab("Adjusted DDE")+
  labs(fill="Race")+
  xlab("")+
  facet_grid(~"Adjusted DDE by group")
p1 = ggarrange(pcb_race, dde_race, ncol=2, 
          common.legend = T, legend = "bottom")
@
\begin{figure}
  \centering
  \includegraphics[width=0.8\textwidth]{Fig1-Adjusted_exposure_gestgroup.png}
\caption{Relationship between delivery group and adjusted exposures, by race}
\label{fig:p1}
\end{figure}
\end{frame}

\begin{frame}{EDA (II) - Exposure across centers}
% Ask Raphael to do this. Need a slide with distribution of DDE and PCB or gestgroup across centers
\end{frame}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Model 1                    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Model (I) - Ordinal Logistic Regression}
% Insert here the AIC part
\begin{frame}{Model (I) - Ordinal Logistic Regression}
\footnotesize
After an AIC backward variable selection procedure, our final model is:
\begin{align*}
textrm{logit}(P(gestgroup_i \leq j)) = \beta_{0j} - &\eta_1adjDDE_i - \eta_2adjPCB_i \\
&-\eta_3 race_i \\
&-\eta_4adjDDE_i*race_i -\eta_4adjDDE_i*race_i \\
&- \sum_{j = center}\eta_{3,j}center_{j,i} + \eta_4smoke_i \eta_4adjDDE_i\boldsymbol{\xi}^T\mathbf{z}_i + \varepsilon_i
\end{align*}
where 
\begin{itemize}
\item $j = 0,1,2$ is the outcome level
\item $DDE_i$ and $PCB_i$ are the amount of DDE and PCB
\item $lipid_i$ measures the lipid deposit 
\item $\mathbf{z}_i$ is a set of covariates. 
\end{itemize}
After an AIC backward , we determine that $\mathbf{z}_i = (center_i, score\_education_i)$\\
Model assumptions are checked in the appendix.
\end{frame}



\begin{frame}{EDA (II) - Exposure across centers}
\begin{align*}
	\textrm{logit}(P(gest_i \leq j)) = \beta_{0j} - \mathbf{X} \mathbf{\beta}_i + \varepsilon_i
\end{align*}

where $j = 0,1,2$ corresponds to the outcome level, and \textbf{X} contains:
\begin{itemize}
	\item DDE, PCB, race, center, smoke, the 3 scores [main effects]
	\item (DDE + PCB) * (race + center) [interactions].
\end{itemize}

AIC-based backward variable selection:
\begin{itemize}
	\item DDE, PCB, \dots, (PCB + DDE) * race
	\item (DDE + PCB) * center is not retained
\end{itemize}

Model assumptions are checked in the appendix.
\end{frame}

% https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3812826/#R13
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Model 2                   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Model (II) - Bayesian Ordinal Logistic Regression}
\begin{frame}{Model (II) - Bayesian Ordinal Logistic Regression}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Results}
\begin{frame}{Results}
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Conclusions                  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Conclusions}
\begin{frame}{Conclusions}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Appendix                 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\appendix
\section{Appendix}
\begin{frame}{Appendix (I) - More EDA}
\begin{figure}
  \centering
  \includegraphics[width=0.6\textwidth]{corrplot_PCB.png}
\caption{Correlation plot across PCBs}
\label{fig:corrPCB}
\end{figure}
\end{frame}
\begin{frame}{Model Checking}
We can check the assumption of the (frequentist) ordinal logistic model by looking at the Surrogate residuals.
If the model assumptions are correct, then the surrogate residuals $R_S$ will have three properties:
\begin{itemize}
 \item $E(R_S|X)=0$
 \item $Var(R_S|X)=c$, the conditional variance of $R_S$ is constant
 \item The emiprical distribution of $R_S$ resembles an explicit distribution that is related to the link function $G^{-1}(\cdot)$. Specifically, $R_S\sim G(c+\int ud G(u))$.
\end{itemize}
\end{frame}

\end{document}