\documentclass{beamer}
\usetheme{Madrid}

%%%%% Packages %%%%%
\usepackage{algorithm}
\usepackage{csquotes}
\usepackage[round]{natbib}
\bibliographystyle{agsm}
\usepackage{algorithmic}
\usepackage{pgfpages}
\usepackage{ragged2e}
\usepackage{etoolbox}
\usepackage{lipsum}
\usepackage{subfig}
\apptocmd{\frame}{}{\justifying}{} 
\usepackage{xcolor}
\usepackage{dsfont}
\usepackage{tikz}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{subfig}
\usepackage{mathtools}
\usepackage{xcolor}
\usepackage{comment}
\usepackage{appendixnumberbeamer}
%%%%% New Commands %%%%
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\x}{\mathbf{x}}
\newcommand{\SUN}{\textrm{SUN}}
\newcommand{\X}{\mathbf{X}}
\newcommand{\T}{\textrm{T}}
\newcommand{\A}{\mathcal{A}}
\newcommand{\I}{\mathds{1}}
\newcommand{\hist}{\mathbb{H}_{t-1}}
\newcommand\myeq{\stackrel{\mathclap{\normalfont\mbox{def}}}{=}}
\def\app#1#2{%
  \mathrel{%
    \setbox0=\hbox{$#1\sim$}%
    \setbox2=\hbox{%
      \rlap{\hbox{$#1\propto$}}%
      \lower1.1\ht0\box0%
    }%
    \raise0.25\ht2\box2%
  }%
}
\def\approxprop{\mathpalette\app\relax}
%\pgfpagesuselayout{1 on 1}[a4paper,border shrink=5mm]
\title[DDE and PCB effect on Premature delivery]{Assessing Effects of Exposures to DDE and PCBs on Premature Delivery via Ordinal Logistic Regression}
\author[Morsomme, Ou, Zito]{Raphael Morsomme \and Rihui Ou \and Alessandro Zito}
\institute[Stat 723]{Case Study 1- Stat 723}
\date{\today}
\begin{document}
\begin{comment}
<<echo=F, results='hide', cache=TRUE>>=
suppressMessages(library(tidyverse))
ggplot2::theme_set(ggplot2::theme_bw())
d = readRDS("Longnecker.rds") %>% 
  filter(gestational_age <= 45) %>%
  mutate(outcome_2 = case_when(gestational_age <= 37 ~ "Pre term",
                               TRUE                  ~ "At term"),
         outcome_3 = case_when(gestational_age <= 34 ~ "0Dangerous",
                               gestational_age <= 37 ~ "1Pre term",
                               TRUE                  ~ "2At term")) %>%
  mutate(outcome_3 = outcome_3 %>% factor) 
ggplot(d) +
  geom_histogram(aes(x=gestational_age), bins=20, 
                 alpha = 0.5,
                 color = "Navy",
                 fill = "Royalblue") +
  geom_vline(xintercept = 34,color = "red") +
  geom_vline(xintercept = 37,color = "blue") +
  xlab("Gestational Age") +
  ylab("") +
  facet_grid(~"Distribution of women in the three groups")+
  annotate(geom="text", x=30, y=300, label="Dangerous preterm",
              color="red") +
  annotate(geom="text", x=35.5, y=300, label="Preterm",
              color="blue") +
  annotate(geom="text", x=42.5, y=300, label="At term")
@
\end{comment}
\begin{frame}
\titlepage
\end{frame}

\begin{frame}{Overview}
\tableofcontents
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Introduction                       
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
\begin{frame}{Introduction}
\begin{itemize}
\item \textcolor{red}{\textbf{Framework}}: \\
\textit{Dichlorodiphenyldichloroethylene} (DDE) and \textit{Polychlorinated Biphenyls} (PCBs) 
are chemicals that persist in the envirnoment and get stored in fatty depositis in the human tissues.\\
$\quad \Longrightarrow \ $\textcolor{blue}{Potential adverse effect on health}
\item \textcolor{red}{\textbf{Question}}:\\
\textit{Is exposure to DDE and PBCs associated with a higher chance of premature delivery in pregnant women?}
\end{itemize}
\begin{block}{Pregnancy timeline}
\begin{itemize}
\item \textbf{Dangerous preterm}:  delivery at 34 weeks or before (when main organs are underdeveloped)
\item \textbf{Preterm}: delivery beween 35 and 37 week
\item \textbf{At term}: delivery after 37 weeks
\end{itemize}
\end{block}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% The Data                       
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Data}
\begin{frame}{Data}
\footnotesize
Data contained gestational age (in weeks) of the mother, the DDE and PCBs concentration, socio-economic info and scores (race, occupation, education and income), and amount of triglycerides and cholesterol. Total sample size (after preprocessing) = 2336\\
\textbf{We contruct the following variables}:
\begin{itemize}
\item Total level of lipids\footnote{Using Phillips et al.(1989) and Bernert et al.(2007)} $$lipid_i =  2.27 * cholesterol_i + triglycerides_i + 0.623$$ 
\item Gestational age group $$gestgroup_i = 
\begin{cases}
0 & if \ \textrm{Dangerous preterm} \\
1 & if \ \textrm{Preterm} \\
2 & if \ \textrm{At term} 
\end{cases}$$
\item Average (standardized) PCB $$PCB_i = \frac{1}{11}\sum_{j=1}^{11} \frac{PCB_{ij} - mean_i(PCB_{ij})}{sd_i(PCB_{ij})}$$
\end{itemize}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Model 1                    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Model (I) - Ordinal Logistic Regression}
% Insert here the AIC part
\begin{frame}{Model (I) - Ordinal Logistic Regression}
We run the following ordinal logistic regression model:
$$\log \frac{P(gestgroup_i \leq j)}{P(gestgroup_i > j)} = \beta_{0j} - \eta_1\frac{DDE_i}{lipid_i} - \eta_2\frac{PCB_i}{lipid_i} - \boldsymbol{\xi}^T\mathbf{z}_i + \varepsilon_i$$
where 
\begin{itemize}
\item $j = 0,1,2$ is the outcome level
\item $DDE_i$ and $PCB_i$ are the amount of DDE and PCB
\item $lipid_i$ measures the lipid deposit 
\item $\mathbf{z}_i$ is a set of covariates. 
\end{itemize}
After an AIC backward variable selection procedure, we determine that $\mathbf{z}_i = (center_i, score\_education_i)$\\
Model assumptions are checked in the appendix.
\end{frame}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Model 2                   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Model (II) - Bayesian Ordinal Logistic Regression}
\begin{frame}{Model (II) - Bayesian Ordinal Logistic Regression}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Results}
\begin{frame}{Results}
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Conclusions                  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Conclusions}
\begin{frame}{Conclusions}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Appendix                 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\appendix
\begin{frame}{Appendix}
\textcolor{red}{\textbf{Preprocessing}}:
{\small
\begin{itemize}
\item Drop obs. with gestational age $>$ 45 (the world record)
\item Standardize and average the differnt PCBs (to avoid their correlation)
\item Mean impute of occupation, education and income scores 
$\quad \Longrightarrow$ Total obs. = 2336
\end{itemize}}
\end{frame}

\begin{frame}{Model Checking}
We can check the assumption of the (frequentist) ordinal logistic model by looking at the Surrogate residuals.
If the model assumptions are correct, then the surrogate residuals $R_S$ will have three properties:
\begin{itemize}
 \item $E(R_S|X)=0$
 \item $Var(R_S|X)=c$, the conditional variance of $R_S$ is constant
 \item The emiprical distribution of $R_S$ resembles an explicit distribution that is related to the link function $G^{-1}(\cdot)$. Specifically, $R_S\sim G(c+\int ud G(u))$.
\end{itemize}
\end{frame}

\end{document}